### ISSUE TITLE
[Errno 2] No such file or directory: '/var/lib/dnf/groups.json'

### ISSUE THREAD

**Issue by MichaelMraka** [edynox/libdnf#2]
when running transformer script (no dnf group command was ever used so there's noo groups.json)
# swdb_transformer.py

Database transformation running
Transforming packages
Transforming transactions
Transforming yumdb
Transforming groups
Traceback (most recent call last):
  File "../libhif.git/python/swdb/swdb_transformer.py", line 489, in <module>
    with open(groups_path) as groups_file:
FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/dnf/groups.json'

**Comment by edcuba** [comment]
Sorry, there was outdated version in libhif, that is allready fixed in dnf_softb
